### ISSUE TITLE
Error with custom validator and async functions

### ISSUE THREAD

**Issue by hongkongkiwi** [danmilon/assurance#3]
I'm writing a custom validator for checking a duplicate account email, for example:

``` javascript
    Accounts.findByUsername(val, function(err, account) {
        if (account) {
            return {type: 'DuplicateAccountEmail',
                    message: 'an account already exists with that email',
                    param: 'email'};
        }

        return;
    });
```

The problem is, because Accounts.findByUsername is asynchronous it returns immediately and the validator happily continues on. In theory the validation function should have a callback rather than return that way it will pause until I call the callback.

**Comment by danmilon** [comment]
Do any async tasks you need _before_ doing the validations. eg

``` javascript
var o1 = { username: 'foo' }

async(function (err, o2) {
  var assure = assurance(o1)
  assure.me('username').notEquals(o2.username)
})
```

If that solves your issue, feel free to close it.

**Comment by hongkongkiwi** [comment]
Hi yes, this solves the problem, makes total sense not sure why I didn't think of it.
